version: '3.7'
services: 
    some-flask-api:
        build: 
            context: .
            dockerfile: Dockerfile_1
        volumes: 
            - .:/app
        expose:
            - "5000"
        ports:
            - "5000:5000"
        links:
            - postgres:postgres
        env_file:
            - .env
        command: "gunicorn --bind 0.0.0.0:5000 wsgi:app"
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        env_file:
            - database.env
        volumes:
            - flask-app-db-data:/var/lib/postgresql/data
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile_2
        ports:
            - "80:80"
        links:
            - some-flask-api:some-flask-api
volumes:
    flask-app-db-data:
